###
# @format
# -----
# Project: @eventiva/eventiva
# File: discord_changelog.yml
# Path: \projects\modules\grand_theft_auto\.github\workflows\discord_changelog.yml
# Created Date: Sunday, January 14th 2024
# Author: Jonathan Stevens, jonathan@resnovas.com
# Github: https://github.com/TGTGamer
# -----
# Contributing: Please read through our contributing guidelines.
# Included are directions for opening issues, coding standards,
# and notes on development. These can be found at
# https://github.com/eventiva/eventiva/blob/develop/CONTRIBUTING.md
# -----
# Code of Conduct: This project abides by the Contributor Covenant, v2.0
# Please interact in ways that contribute to an open, welcoming, diverse,
# inclusive, and healthy community. Our Code of Conduct can be found at
# https://github.com/eventiva/eventiva/blob/develop/CODE_OF_CONDUCT.md
# -----
# Copyright (c) 2024 Resnovas - All Rights Reserved
# LICENSE: GNU General Public License v2.0 or later (GPL-2.0-or-later)
# -----
# This program has been provided under confidence of the copyright holder and
# is licensed for copying, distribution and modification under the terms
# of the GNU General Public License v2.0 or later (GPL-2.0-or-later) published as the License,
# or (at your option) any later version of this license.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License v2.0 or later for more details.
# You should have received a copy of the GNU General Public License v2.0 or later
# along with this program. If not, please write to: jonathan@resnovas.com,
# or see https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html
# -----
# This project abides by the GPL Cooperation Commitment.
# Before filing or continuing to prosecute any legal proceeding or claim
# (other than a Defensive Action) arising from termination of a Covered
# License, we commit to extend to the person or entity ('you') accused
# of violating the Covered License the following provisions regarding
# cure and reinstatement, taken from GPL version 3.
# For further details on the GPL Cooperation Commitment please visit
# the official website: https://gplcc.github.io/gplcc/
# -----
# DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE
###

name: 'Change Report'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 01 * * 1/2'
permissions:
  contents: read

jobs:
  change-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Use a large enough fetch depth to ensure the action can find the commit history to work with
          fetch-depth: 250

      - uses: eventiva/change-report@main
        with:
          # The destination to post the report to.
          # "slack" and "discord" are supported
          destination: 'discord'
          # Number of days to include into the report
          days: 2
          # Slack channel to post the report to.
          # For Slack it's the name of the channel, without the leading "#",
          # For Discord it's the channel ID
          channel: '1181345448452182106, 1175861376711925762'
        env:
          # Your OpenAI API key, used to generate the report
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Your Slack bot token, used to post the report on behalf of the bot.
          # Only needed if you're posting to Slack
          # SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          # Your Slack signing secret, used to verify the request is coming from Slack
          # Only needed if you're posting to Slack
          # SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          # Your Discord bot token, used to post the report on behalf of the bot.
          # Only needed if you're posting to Discord
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GITHUB_REPO_NAME: ${{ github.repository }}
